### ISSUE TITLE
Request - add @media print to carry over full styles to PDF exports

### ISSUE THREAD

**Issue by VanWeapon** [dracula/obsidian#29]
When exporting to PDF using this theme, a lot of the colours such as the different headings come across to the generated PDF but the overall theme gets more or less switched out for a light mode. Background colour is white and text is black, this contrasts poorly with the rest of the theme, so currently to get a good looking export you would have to change theme back to default or a light theme before exporting. 

Seems that you can write a CSS `@media` query to customise the appearance of generated PDFs, I tried doing this with limited success, CSS is not my strong suit.

My very rudimentary css snippet below gets me like 80% there, but doesn't handle `pre` code snippets well as it adds bg colour to the text within the block.
e.g.
![image](https://user-images.githubusercontent.com/30616047/218307375-933d6115-2a2c-4c9e-945e-512e8810daf4.png)

I'm also struggling to change tag links from italicised blue to non-italic green, the `a` tag selector doesn't work. 
e.g.
In obsidian:
![image](https://user-images.githubusercontent.com/30616047/218307424-0bfb4b06-cdf0-4690-aada-85ffb2374c29.png)

In pdf
![image](https://user-images.githubusercontent.com/30616047/218307436-acc09ec5-8f54-43d1-943b-a07ba4cc1fd4.png)

Hopefully the experts here could take my starting point and polish it up to make it production ready:
```css
@media print {
	* {
		background-color: #282a36;
	}

	@page {
		margin: 0mm 0mm 0mm 0mm;
	}
	body {
		margin: 0mm 0mm 0mm 0mm;
	}
	span,
	li,
	p {
		color: #f8f8f2;
	}
}
```
