### ISSUE TITLE
Why is the font for links overriding global preferences

### ISSUE THREAD

**Issue by JDENredden** [dracula/obsidian#36]
I have a monospace font (Berkeley Mono) as my editor font. Howoever, I've noticed that links with this theme are rendered with sans-serif font.

So I did some investigating and found out that inside obsidian.css on line 28-36

```css
a,
.internal-link,
.cm-hmd-internal-link,
.cm-link,
.cm-formatting-link {
  color: var(--text-a) !important;
  text-decoration: none !important;
  font-family: Avenir, Avenir Next, sans-serif !important;
}
``` 

The links are given an !important override as a sans-serif font. 

Why is this? Why doesnt this follow the user's global choice? Can this be changed to not do this? I don't really want to have to manually install this theme to correct this one issue.
