### ISSUE TITLE
Content width narrows as I increase the window/pane width

### ISSUE THREAD

**Issue by raulrpearson** [dracula/obsidian#6]
With a narrow window/pane, I get this:

<img width="942" alt="narrower-means-wider" src="https://user-images.githubusercontent.com/23662058/122673536-91d9a380-d1d9-11eb-8c33-5856725896af.png">

But as I make the window/pane wider, the content column becomes narrower:

<img width="2656" alt="wider-means-narrower" src="https://user-images.githubusercontent.com/23662058/122673555-a28a1980-d1d9-11eb-89fc-283d5d3ea13a.png">

Is anybody else experiencing this? Is it due to something wrong with my setup?

This only seems to be an issue in edit mode, not in preview.

**Comment by raulrpearson** [comment]
If I remove [these padding lines](https://github.com/dracula/obsidian/blob/66ca0cb0cb9cea08cfb03fd31455a776c9a570f7/obsidian.css#L656), it seems to improve the situation:

```css
/* editor */

.cm-s-obsidian {
  font-family: var(--font-family-editor);
  font-size: 15px;
  color: var(--text-normal);
  padding-left: 8% !important;
  padding-right: 4% !important;
}
```

But I can see this 8%/4% pattern in several places. I'm not familiar with Obsidian styling and don't have much time to spend on this, so any tips welcome.
